name: socket_io_client
description: Dartlang port of socket.io-client for web, flutter, dartvm to use
version: 1.0.2
homepage: https://www.zkoss.org
repository: https://github.com/rikulo/socket.io-client-dart
issue_tracker: https://github.com/rikulo/socket.io-client-dart/issues

environment:
  sdk: ^3.5.0

dependencies:
  socket_io_common: '^1.0.0'
  js: '^0.7.1'
  logging: '^1.0.1'


dev_dependencies:
  socket_io: any
  build_runner: any
  build_web_compilers: any
